export const TYPES = {
  ADD_QUOTE: 'ADD_QUOTE',
  ADD_KEY_PRESSED: 'ADD_KEY_PRESSED',
  REMOVE_KEY_PRESSED: 'REMOVE_KEY_PRESSED',
  MARK_AS_COMPLETED: 'MARK_AS_COMPLETED',
  CALCULATE_RESULTS: 'CALCULATE_RESULTS',
  UPDATE_QUOTE: 'UPDATE_QUOTE',
  RESTART: 'RESTART'
}
